### PR TITLE
Allow to use original item id

### PR DESCRIPTION
**Pull request by Buri**
BC compatible

### CODE REVIEW

**Comment by Raydiation** [comment]
That would give you title, link and content if the rss feed does not provide a guid (which is optional according to spec). Id rather add another getter like $item->getOriginalId(). That way you can also combine both.

Can I ask why you want the original id btw?

**Comment by Buri** [comment]
Some of the feeds have additional or non standart informations i want to access and i need to refference different items.

**Comment by Raydiation** [comment]
Can you elaborate?

**Comment by mkresin** [comment]
> BC compatible

What does this mean?

I would vote for a new getter as well. The change to ```generateId()``` looks like a workaround.

**Comment by Raydiation** [comment]
I suppose it's sometimes useful to access protocol specific tags/attributes. Maybe we could provide a generic getter on an item/feed that lets you fetch attributes/content of any tag that's available, maybe something like getTagContent($tag, $default)

That way we keep the cross feed api while still giving api users the power to use protocol specific stuff

**Comment by fguillot** [comment]
@mkresin I think BC = "Backward Compatible"...

I'm ok to use a new method to get original values but that means we need to store the raw xml inside the feed object.

**Comment by fguillot** [comment]
There is new method to fetch original tag value, examples:

```php
echo $feed->items[0]->getTag('guid');
```

More info here: https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown#get-raw-xml-tagsattributes-or-non-standard-tags-for-items

**Pull request closed without merging**
