### PR TITLE
grabber & filter fixes

### PR DESCRIPTION
**Pull request by mkresin**
__Filter: do not filter empty content:__ 

The ```DOMXpath()``` in ```PicoFeed\Filter\Tag->removeBlacklistedTags( )``` throws a fatal error if the feed item content is empty. ```XmlParser::getDomDocument($data)``` returns false on empty data, where ```DOMXpath()``` expects an instance of DOMDocument as argument.

__Grabber: use encoding specified in html content__

This one is exposed by the switch to iconv for charset conversion.

### CODE REVIEW

**Comment by mkresin** [comment]
@Raydiation any feedback on this is highly welcome.

**Comment by Raydiation** [comment]
:+1:

**Comment by mkresin** [comment]
I've changed the "do not filter empty content" commit once more. Looks way more cleaner now and covers a few more corner cases like content items that contain only whitespaces.

**Comment by mkresin** [comment]
Sorry, the close of the miniflux ticket was not intended.

**Comment by fguillot** [comment]
It's not your fault, Github have this behaviour by default.

**Pull request merged**
