### PR TITLE
Update Engadget rules.

### PR DESCRIPTION
**Pull request by ZacharyDuBois**
Fixes miniflux/miniflux#442.

### CODE REVIEW

**Comment by ZacharyDuBois** [comment]
No idea why it failed. Just tested on my Miniflux instance, worked fine.

**Comment by mkresin** [comment]
The failed test is not related to you commit.

**Comment by ZacharyDuBois** [comment]
@mkresin Ah alright. Awesome.

**Comment by BernhardPosselt** [comment]
:+1:

**Pull request merged**
