### PR TITLE
use only iconv for charset conversion

### PR DESCRIPTION
**Pull request by mkresin**
Has anyone experiences whether utf-8 characters in not utf-8 strings are a common problem?

I've checked against all my subscribed feeds and neither have encoding f*ckup nor any notices/warnings from php.

Feedback and more real world tests are highly welcome.

### CODE REVIEW

**Comment by mkresin** [comment]
Forgot to mention that picoFeed - even with the last commit - does not support all windows codepages and more questions to support a particular encoding are to be expected.

At least the following codepages/encodings are unsupported:

- Windows-1250 - Polish, Czech, Slovak, Hungarian, Slovene, Bosnian, Croatian...
- Windows-1253 - Greek
- Windows-1254 - Turkish
- Windows-1257 - Baltic
- Windows-1258 - Vietnamese
- every iso encoding other than iso-8559-1

**Comment by Raydiation** [comment]
This is a breaking change and another lib dependency correct? I'm not against it but we should have a changelog somewhere where we note the breaking changes

**Comment by mkresin** [comment]
> This is a breaking change

Yes and no. As long as the feed character encoding and the announced charset match, it should work as before. Only corner cases where the feed character encoding does not match the announced charset will have issues.

That's why I ask everyone who could be affected from this changeset, to tests against real world feeds. I've no clue what kind of malformed encoded feeds exist out there and how common they are. All my used feeds are encoded correctly. This knowledge is mandatory to handle at least common encoding faults.

> and another lib dependency correct?

Not exactly. Iconv is used for windows-1251, windows-1255 and windows-1256 already.

**Comment by Raydiation** [comment]
What I mean is that you have to enable iconv in the php.ini file as extension=iconv.so 

If this is not enabled the call to iconv will result in an unknown function call and it will generate an error :) Thats what I meant with breaking change

**Comment by Raydiation** [comment]
So ownCloud news must define this as a lib dependency on installation

**Comment by mkresin** [comment]
I understood what you mean. But the dependency to iconv.so was already introduced 3. Oct 2014 with commit bfa6fb2815218960b3de7f94cfd8bade29ce793c. That's why I would not say that exactly this is a breaking change. May you did not get any bugreports because the usage was limited to not latin charsets.

Anyway, the dependency to iconv.so needs to be mentioned in the docs.

**Comment by Raydiation** [comment]
Ah, I see. Then it's missing here https://github.com/fguillot/picoFeed#requirements 

Can you update it in your PR?

**Comment by mkresin** [comment]
@Raydiation, @fguillot 

As expected the first issues appeared because of this change: https://github.com/miniflux/miniflux/issues/332. Should we react on this or should we handle this as known issue because of shortcomings on the remote side?

A complete failing feed is limited to cases where the http encoding header is missing AND the xml encoding information is missing AND the feed is not utf-8 encoded AND characters different from us-ascii are used.

The worst that can happen if the announced encoding does not match the used encoding, are missing (non us-ascii) characters.

**Comment by Raydiation** [comment]
Yep, no problem, feed author needs to fix his feed.

**Comment by fguillot** [comment]
For completely broken feeds I think it's a waste of time to add quick and dirty workarounds.

**Comment by mkresin** [comment]
Obviously we've all the same opinion on this. Good to know.

**Pull request merged**
