### PR TITLE
Add a way to define multiple rules based on a regex which is matched aga...

### PR DESCRIPTION
**Pull request by Raydiation**
...inst the full path url

Implementation for #130 and #128

Please review carefully!

### CODE REVIEW

**Comment by Raydiation** [comment]
@fguillot @mkresin

**Comment by mkresin** [comment]
Can you please refer to a php manual page that explains the the behaviour of the percent sign? Even after using regex for more than a decade, I wasn't aware of it's special meaning.

What I read so far is, that almost all of the special characters are handled as ordinary characters. Till now, I couldn't find a document that explains which special characters are escaped by the percent sign in php.

**Comment by mkresin** [comment]
One more thing™. Would it be possible to add a test for this new functionality?

**Comment by Raydiation** [comment]
The first character is always the delimiter. The php doc uses / in its documentation but actually it doesnt matter. I chose % because urls contain lots of slashes and that way you dont have to escape them.

**Comment by Raydiation** [comment]
Will add a test :) sec

**Comment by mkresin** [comment]
I recommend to change the delimiter to  '/'. It's less confusing. A slash is the "normal" way, used in the php docs and nearly everywhere else. Finally, as already pointed out, it has a special meaning for some regex implementations.

**Comment by Raydiation** [comment]
Here's the doc http://php.net/manual/en/regexp.reference.delimiters.php btw, there are no special meanings for the % sign and phps implementation in this regard. We can add that to the grabber docs if you find it confusing. 

However since most regexes are just **%.*%** I can change that. I will however use the % sign as a delimiter for the rules that use something other than /.*/ and contain slashes, since it is way more readable IMHO. I think the regex readability counts more than the first and last character ;)

Or should we just keep everything like it is now? IMHO there are no real downsides...

**Comment by mkresin** [comment]
I don't want to argue what's better. For me, a slash is THE regex delimiter and used by all implementations I'm aware of.

Two people, two opinions. Fortunately, the judge have to decide what get committed and what not.

**Comment by Raydiation** [comment]
Also implemented #128

**Comment by Raydiation** [comment]
BTW: After this PR is in, I'll migrate our stuff to picofeeds rules and send another PR :)

**Comment by fguillot** [comment]
I merged your pull-request.

The grabber class need some refactoring, the code start to become messy...

**Comment by mkresin** [comment]
@Raydiation Still interested in comments/questions on this PR? Frédéric committed your changes before I had the time to review this completely. You know, good weather in Germany and a lot of other stuff to do.

**Comment by oparoz** [comment]
I just want to add that using different delimiters for regular expressions is quite common, especially when having to deal with string which may contain slashes.

**Pull request merged**
