### PR TITLE
Favicon tag detection fix.

### LINKED ISSUE #231: Favicon extract pulls wrong icons
There's an issue with Favicon extract() function on www.smashingmagazine.com website (and possibly others). rel="mask-icon" is picked up as favicon and returned in icons array. Query used in extract() function needs to be more specific, not to pick up invalid favicons.

### PR DESCRIPTION
**Pull request by joshas**
Closes #231.

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
:+1: tested and works

**Comment by mkresin** [comment]
Well, it was done this way for a specific reason. Have a look at the following testcase https://github.com/fguillot/picoFeed/blob/master/tests/Reader/FaviconTest.php#L27.

Maybe pointless to say, but this test fails now.

So we either:

a) change the test and accept that broken favicon tags don't work any longer or
b) we add another exclusion similar to the apple thingy.

I prefer a).

**Comment by BernhardPosselt** [comment]
The favicon also shouldn't work in a browser right? So it should be no surprise

**Comment by mkresin** [comment]
> The favicon also shouldn't work in a browser right?

I wouldn't bet on it. As far as I can see, there are only best practice recommendations on how to add a favicon to a website. Something like a hard standard doesn't seam to exist.

**Comment by BernhardPosselt** [comment]
http://www.w3.org/2005/10/howto-favicon

**Comment by mkresin** [comment]
Well, a draft from 2005. Nothing what I would call a standard or even a recommendation. Kinda outdated compared to real world usage (no mention of icon resolutions, touch icons or even svg).

Anyway, no need to argue about that.

**Pull request merged**
