### PR TITLE
Added hhvm to tests

### PR DESCRIPTION
**Pull request by JanPetterMG**

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Good idea!

**Comment by JanPetterMG** [comment]
Is there any way to restart the test, other than commit another change?
Seems like curl timed out, build terminated and no test results given...

**Comment by JanPetterMG** [comment]
PHP 7 test failed due to connection problems and the hhvm test always hangs before it times out.

The travis.yml now allows hhvm to fail, without failing the build. Restart the build (whoever have access to do that), and the build will succeed.

**Comment by BernhardPosselt** [comment]
At some point we should grab a local copy of the rss/atom feeds under test and spin up a quick local server for them. These tests are kinda brittle although it looks like hhvm has issues

**Pull request merged**
