### PR TITLE
add passthrough download mode,  add option to limit image proxying to a specific protocol

### PR DESCRIPTION
**Pull request by mkresin**
__add passthrough download mode__

It's meant to be used by image proxies that are backed by picoFeed functions
like the image proxy in miniflux.

__add option to limit image proxying to a specific protocol__

reverts d3785fc and implements an option to
set the targeted protocol.

One use case where the image proxy should be used with HTTPS urls is referrer
cloaking.

### CODE REVIEW

**Comment by Raydiation** [comment]
BTW: why are you using these image proxies :) ? do you know of the xss risk?

**Comment by mkresin** [comment]
> why are you using these image proxies

prevent mixed content warnings when connected via https to miniflux; remove the referrer to bypass hotlinking protection which is used by http://www.neowin.net/ for example

> do you know of the xss risk?

Yeap. That's why miniflux uses CSP to prevent the execution of inline javascript.

**Comment by Raydiation** [comment]
You can add JavaScript in svg images ;D

**Comment by Raydiation** [comment]
https://www.owasp.org/images/0/03/Mario_Heiderich_OWASP_Sweden_The_image_that_called_me.pdf

**Comment by fguillot** [comment]
@Raydiation How do you handle this problem (mixed content warnings) with Owncloud?

**Comment by Raydiation** [comment]
I've tried to handle it but there are no real solutions. What I do for instance is to default to prepend https when a user just enters www.site.com. 

There are different security levels for mixed content: active and passive, see https://developer.mozilla.org/en-US/docs/Security/MixedContent

In regards to passive content, a MITM attack could only alter the images in the worst case but not access or modify the page. The important thing is to prevent the active content such as scripts, links, iframes, css url values and objects with the data attribte. Everything is blacklisted by content filtering using HTMLPurifier except iframes from youtube and vimeo which are usually added using https.

Now that I mention it, I should probably only whitelist https iframes xD https://github.com/owncloud/news/blob/master/appinfo/application.php#L127

**Comment by Raydiation** [comment]
Pushed a fix to ownCloud News for https iframes btw :)

**Comment by Raydiation** [comment]
BTW not all browsers fully support CSP. Firefox only recently started to support it and IE is a real problem, check http://caniuse.com/#search=csp 

And dont forget the android browser, only android 4.4+ supports it

**Comment by mkresin** [comment]
Well I've checked the image proxy with the rough svg http://www.kresin.me/javascript.svg. At least firefox, chrome & internet explorer 11 do not display the alert. That doesn't mean that it not possible, but at least it is not that easy.

**Comment by mkresin** [comment]
One more word on this. We can only limit the attack surface, but finally it's the browsers job to prevent javascript execution from the img src attribute for example.

**Comment by Raydiation** [comment]
Btw you are just silencing the error message with the proxy. The real problem is that the original source does not offer https. Now if you are putting an image proxy in between you are still vulnerable to mitm, the problem is just shifted to the image proxy and even worse: your users think that this is now safe although it isn't really ;)

The only thing that probably helps is to write a tool that raises flags for http resources in feeds, something like the w3c validator that makes it easy to test for insecure feeds. That could apply some pressure

**Comment by mkresin** [comment]
I'm glad that we have this discussion and generally I share your security concerns.

I've done my first MITM attack approximately a decade ago using arp spoofing and still doing MITM attacks to analyse/understand the inner workings of TLS encrypted protocols. It's a mess to see how many applications, which targeting a single hardcoded endpoint, accept certificates for this endpoint issued from any CA. Since I'm a network/system guy, I've way more knowledge about abusing the protocol layer (MITM) than the application layer (XSS).

First of all we should summarise in what situations the images proxy is tend to be used:

- only if the user is connected via https to miniflux
- only for images
- only for images served via http (there is one possible exception to this, but this needs to be discussed later)

Furthermore we're talking about public feeds, which contain images that are used to illustrate an article. It's not about authentication data or two factor authentication qr code images.

Last but not least, the image proxy is default of and needs to be enabled by the user.

> Now if you are putting an image proxy in between you are still vulnerable to mitm, the problem is just shifted to the image proxy and even worse: your users think that this is now safe although it isn't really ;)

Nope, it doesn't change the game! Independent of the usage of an image proxy, the user has no chance to notice that (s)he is under MITM attack if the images are served via HTTP.

But the image proxy moves the MITM attack vector to the connection between the server where miniflux runs and the endpoint that serves the image. Using the image proxy, it is possible to verify that unencrypted content isn't altered on the way from the miniflux server to the users browsers.

If we have a look at the server side, it's getting even worse. I assume that johnny average uses a shared hoster and simply drops of the php files into his public_html dir. Johnny has no control which certificates the local server trusts, may the php binary is altered to accept any certificates. That is the point where a MITM attack is a easy game.

On the other side I assume that shared hoster know there job. Based on my personal experiences it's more likely that the users (desktop) system is compromised by malware.

> The only thing that probably helps is to write a tool that raises flags for http resources in feeds, something like the w3c validator that makes it easy to test for insecure feeds. 

I'm not sure what you mean by "flags". I'm assuming you are talking about some kind of notification to the user? I even doubt that this would change anything to the majority of the users.  The average user:

- doesn't care about encryption/security (I've nothing to hide)
- confirms warnings faster than I could read the text
- ignores errors till nothing works anymore

A few days ago someone came up with a patch to disable certificate validation completely, because his windows php binary had no ca certificates bundled. That's how users try to fix there problems.

> That could apply some pressure

If you are talking about the feed creator, forget it. My personal experience is, that companies changing things only if there profit is affected. RSS feeds are more less a disaster for companies that make profit with there textual content. Especially in conjunction with content grabber. No page impressions, no advertisement and so on.

**Comment by mkresin** [comment]
I read a bit about the svg vulnerability. As far I understood it, it is limited to svg in conjunction with object or embed tags. The image tag is not vulnerable.

@Raydiation It's all well. Every notice about a possible security problem is welcome.

@fguillot I've pushed the miniflux counterpart to https://github.com/mkresin/miniflux/tree/imageproxy. I tend to use the referrer cloaking even with content served via https. Well, it breaks the end-to-end encryption, but otherwise the images are not shown for the user.

**Comment by mkresin** [comment]
I'm not entirely happy with the ```disablePassthroughMode()``` function. Neither am I sure that the function is really needed nor that the function name is good one. Maybe it should be named something like ```enableDownloadMode()```.

I've started using the Client classes of picoFeed for another project. Have you ever considered to split of the Client classes into a picoDownload?

**Comment by fguillot** [comment]
@mkresin I didn't plan to make a picoClient or picoDownload library, usually people use popular libraries like https://github.com/guzzle/guzzle or https://github.com/kriswallsmith/Buzz

**Pull request merged**
