### PR TITLE
Parser improvments

### PR DESCRIPTION
**Pull request by mkresin**
Each commit contains a detailed description what has been done.

@Raydiation

### CODE REVIEW

**Comment by Raydiation** [comment]
TBH too big too review, it would be nice if you could split it into separate features in the future. From the first few files looks solid so im giving a :+1:

**Comment by mkresin** [comment]
Beside fixing a small issue, I've splitted the former 14 commits into 16. Hopefully it's better to review now. Otherwise, it would be magnificent if you can give me a hint which commit is "to big to review".

**Comment by fguillot** [comment]
I didn't yet review all your changes, but I suppose there is no issue like the one described in your last comment https://github.com/fguillot/picoFeed/pull/157#issuecomment-112959419 right?

Thanks again, I will try to review/merge that asap.

**Comment by mkresin** [comment]
> I didn't yet review all your changes, but I suppose there is no issue like the one described in your last comment #157 (comment) right?

Right! All XPath querries will be tranformed by ```replaceXPathPrefixWithNamespaceURI()``` to make sure that only values of this specific namespace are returned.

> I will try to review/merge that asap.

Take your time! I'm not in hurry to get this merged.

**Pull request merged**
