### PR TITLE
silence only iconv notices, return input on error

### PR DESCRIPTION
**Pull request by mkresin**
@Raydiation

### CODE REVIEW

**Comment by Raydiation** [comment]
:+1:

**Comment by fguillot** [comment]
Do you know if using `set_error_handler()` can have an impact outside of the library? By example, if an application that use picofeed already use a custom error handler, that will break the application or not?

**Comment by Raydiation** [comment]
The restore error handler should revert everything to normal

**Comment by Raydiation** [comment]
I suppose error handlers are pushed onto a stack and the restore function pops the newest one

**Comment by mkresin** [comment]
I have to admit that I didn't considered that I potentially overwrite an error handler definition by a script that is using picofeed as library.

The documention of ```restore_error_handler()``` seam to confirm Bernhards assumption:

> ... to revert to the previous error handler (which could be the built-in or a user defined function).

And the following test confirms Bernhards assumption finally:

```php
<?php

error_reporting(E_ALL);

set_error_handler(function($errno, $errstr, $errfile, $errline, array $errcontext) {
    $type = array('2' => 'warning', '8' => 'notice');

    echo 'CatchAll Errorhandler: ' .$type[$errno].' - '.$errstr.PHP_EOL;
});

iconv('invalid', 'utf-8', 'string');
iconv();

set_error_handler(function($errno, $errstr, $errfile, $errline, array $errcontext) {
    $type = array('2' => 'warning', '8' => 'notice');

    echo 'Notice Errorhandler: ' .$type[$errno].' - '.$errstr.PHP_EOL;
}, E_NOTICE);

iconv('invalid', 'utf-8', 'string');
iconv();

restore_error_handler();
iconv('invalid', 'utf-8', 'string');
iconv();
```

```
CatchAll Errorhandler: notice - iconv(): Wrong charset, conversion from `invalid' to `utf-8' is not allowed
CatchAll Errorhandler: warning - iconv() expects exactly 3 parameters, 0 given
Notice Errorhandler: notice - iconv(): Wrong charset, conversion from `invalid' to `utf-8' is not allowed

Warning: iconv() expects exactly 3 parameters, 0 given in C:\Arbeitsverzeichnis\privat\git\picofeed\error.php on line 21
CatchAll Errorhandler: notice - iconv(): Wrong charset, conversion from `invalid' to `utf-8' is not allowed
CatchAll Errorhandler: warning - iconv() expects exactly 3 parameters, 0 given
```

I'm a bit upset, that ```set_error_handler(function() {}, E_NOTICE);``` replace the error handler for all kind of errors instead of notices only.

What do you think? Acceptable?

**Comment by Raydiation** [comment]
Yes acceptable since your error handler only runs in that specified block and won't affect any code outside of it

**Pull request merged**
